name: ansible-lint

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ansible-lint
        run: |
          pip3 install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint --sarif-file result.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: result.sarif
          category: ansible-lint-analysis
